/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.45
 * Generated at: 2025-09-13 02:06:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class GmailForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("        <!-- Place the first <script> tag in your HTML's <head> -->\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("            integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Roboto&family=Open+Sans&family=Lato&family=Montserrat&family=Source+Sans+Pro&family=Raleway&family=Oswald&family=Ubuntu&family=Poppins&family=Merriweather&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            .ql-font-roboto {\r\n");
      out.write("                font-family: 'Roboto', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ql-font-open-sans {\r\n");
      out.write("                font-family: 'Open Sans', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ql-font-lato {\r\n");
      out.write("                font-family: 'Lato', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ql-font-montserrat {\r\n");
      out.write("                font-family: 'Montserrat', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ql-font-source-sans-pro {\r\n");
      out.write("                font-family: 'Source Sans Pro', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ql-font-raleway {\r\n");
      out.write("                font-family: 'Raleway', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ql-font-oswald {\r\n");
      out.write("                font-family: 'Oswald', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ql-font-ubuntu {\r\n");
      out.write("                font-family: 'Ubuntu', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ql-font-poppins {\r\n");
      out.write("                font-family: 'Poppins', sans-serif;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ql-font-merriweather {\r\n");
      out.write("                font-family: 'Merriweather', serif;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("\r\n");
      out.write("        <style type=\"text/tailwindcss\">\r\n");
      out.write("            @theme {\r\n");
      out.write("        --color-clifford: #da373d;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("        <style>\r\n");
      out.write("            .item-icon {\r\n");
      out.write("                padding: 3px;\r\n");
      out.write("                margin-left: 4px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon {\r\n");
      out.write("                width: 20px;\r\n");
      out.write("                height: 20px;\r\n");
      out.write("                /* outline: green solid 1px; */\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .item-icon:hover,\r\n");
      out.write("            .item-icon.active {\r\n");
      out.write("                background-color: #ccc9c9;\r\n");
      out.write("                border-radius: 4px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon1 {\r\n");
      out.write("                background: url('https://ssl.gstatic.com/ui/v1/icons/mail/gm3/1x/format_color_text_baseline_nv700_20dp.png') no-repeat;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon2 {\r\n");
      out.write("                background: url('https://ssl.gstatic.com/ui/v1/icons/mail/gm3/1x/attach_file_baseline_nv700_20dp.png') no-repeat;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon3 {\r\n");
      out.write("                background: url('https://ssl.gstatic.com/ui/v1/icons/mail/gm3/1x/link_baseline_nv700_20dp.png') no-repeat;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon4 {\r\n");
      out.write("                background: url('https://ssl.gstatic.com/ui/v1/icons/mail/gm3/1x/mood_baseline_nv700_20dp.png') no-repeat;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon5 {\r\n");
      out.write("                background: url('https://ssl.gstatic.com/ui/v1/icons/mail/gm3/1x/drive_baseline_nv700_20dp.png') no-repeat;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon6 {\r\n");
      out.write("                background: url('https://ssl.gstatic.com/ui/v1/icons/mail/gm3/1x/image_baseline_nv700_20dp.png') no-repeat;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon7 {\r\n");
      out.write("                background: url('https://ssl.gstatic.com/ui/v1/icons/mail/gm3/1x/lock_clock_baseline_nv700_20dp.png') no-repeat;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon8 {\r\n");
      out.write("                background: url('https://ssl.gstatic.com/ui/v1/icons/mail/gm3/1x/ink_pen_baseline_nv700_20dp.png') no-repeat;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .icon9 {\r\n");
      out.write("                background: url('https://ssl.gstatic.com/ui/v1/icons/mail/gm3/1x/more_vert_baseline_nv700_20dp.png') no-repeat;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .trash {\r\n");
      out.write("                background: url('https://ssl.gstatic.com/ui/v1/icons/mail/gm3/1x/delete_baseline_nv700_20dp.png') no-repeat;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            #mytoolbar {\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                top: -44px;\r\n");
      out.write("                left: 0;\r\n");
      out.write("                height: 40px;\r\n");
      out.write("                background-color: white;\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            #mytoolbar.active {\r\n");
      out.write("                display: flex;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            input:focus {\r\n");
      out.write("                outline: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .ql-editor {\r\n");
      out.write("                padding: 0;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"w-[600px] mx-auto my-10 border rounded shadow\">\r\n");
      out.write("            <div class=\"!bg-blue-100 p-[-4px]\">\r\n");
      out.write("                <h1 class=\"!text-[#041e49] !text-[16px] p-2\">Thư mới</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"\">\r\n");
      out.write("                <div class=\"p-3\">\r\n");
      out.write("                    <div class=\"py-1 border-b-1 border-b-[#e9e9e9]\"><input type=\"text\" class=\"border-0  w-full\"\r\n");
      out.write("                            placeholder=\"Người nhận\"></div>\r\n");
      out.write("                    <div class=\"py-1 border-b-1 border-b-[#e9e9e9]\"><input type=\"text\" class=\"border-0 w-full\"\r\n");
      out.write("                            placeholder=\"Tiêu đề\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div name=\"\" id=\"editor\" class=\"resize-none !h-[200px] mt-2 !border-none !text-[16px]\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"flex items-center mt-4 p-3\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary !rounded-xl !px-[40px]\">Gửi</button>\r\n");
      out.write("                    <div class=\"flex ml-[10px] relative\">\r\n");
      out.write("                        <div id=\"mytoolbar\" class=\"flex\">\r\n");
      out.write("                            <select class=\"ql-font\">\r\n");
      out.write("                                <option value=\"sans-serif\" selected>Sans Serif</option>\r\n");
      out.write("                                <option value=\"serif\">Serif</option>\r\n");
      out.write("                                <option value=\"monospace\">Monospace</option>\r\n");
      out.write("                                <option value=\"roboto\">Roboto</option>\r\n");
      out.write("                                <option value=\"open-sans\">Open Sans</option>\r\n");
      out.write("                                <option value=\"lato\">Lato</option>\r\n");
      out.write("                                <option value=\"montserrat\">Montserrat</option>\r\n");
      out.write("                                <option value=\"source-sans-3\">Source Sans 3</option>\r\n");
      out.write("                                <option value=\"raleway\">Raleway</option>\r\n");
      out.write("                                <option value=\"oswald\">Oswald</option>\r\n");
      out.write("                                <option value=\"ubuntu\">Ubuntu</option>\r\n");
      out.write("                                <option value=\"poppins\">Poppins</option>\r\n");
      out.write("                                <option value=\"merriweather\">Merriweather</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <select class=\"ql-size\"></select>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Bold, Italic, Underline -->\r\n");
      out.write("                            <button class=\"ql-bold\"></button>\r\n");
      out.write("                            <button class=\"ql-italic\"></button>\r\n");
      out.write("                            <button class=\"ql-underline\"></button>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Danh sách -->\r\n");
      out.write("                            <button class=\"ql-list\" value=\"ordered\"></button>\r\n");
      out.write("                            <button class=\"ql-list\" value=\"bullet\"></button>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Link -->\r\n");
      out.write("                            <button class=\"ql-link\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item-icon relative\" onclick=\"handleClick(event)\">\r\n");
      out.write("                            <div class=\"icon icon1\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-icon\">\r\n");
      out.write("                            <div class=\"icon icon2\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-icon\">\r\n");
      out.write("                            <div class=\"icon icon3\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-icon\">\r\n");
      out.write("                            <div class=\"icon icon4\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-icon\">\r\n");
      out.write("                            <div class=\"icon icon5\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-icon\">\r\n");
      out.write("                            <div class=\"icon icon6\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-icon\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"icon icon7\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-icon\">\r\n");
      out.write("                            <div class=\"icon icon8\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item-icon\">\r\n");
      out.write("                            <div class=\"icon icon9\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"item-icon !ml-auto\">\r\n");
      out.write("                        <div class=\"icon trash\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        const FontAttributor = Quill.import('attributors/class/font');\r\n");
      out.write("        FontAttributor.whitelist = [\r\n");
      out.write("            'roboto', 'open-sans', 'lato', 'montserrat', 'source-sans-3',\r\n");
      out.write("            'raleway', 'oswald', 'ubuntu', 'poppins', 'merriweather',\r\n");
      out.write("            // giữ luôn mặc định để dropdown gốc hoạt động\r\n");
      out.write("            'sans-serif', 'serif', 'monospace'\r\n");
      out.write("\r\n");
      out.write("        ];\r\n");
      out.write("        Quill.register(FontAttributor, true);\r\n");
      out.write("\r\n");
      out.write("        const quill = new Quill('#editor', {\r\n");
      out.write("            theme: 'snow',\r\n");
      out.write("            modules: { toolbar: '#mytoolbar' }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function handleClick(e) {\r\n");
      out.write("            console.log(e.target);\r\n");
      out.write("            var parent = e.target.closest('.item-icon')\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            const toolbar = document.getElementById('mytoolbar');\r\n");
      out.write("            toolbar.classList.toggle('active');\r\n");
      out.write("            parent.classList.toggle('active')\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
