/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.45
 * Generated at: 2025-09-12 09:27:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class tailieu_005fdangky_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Insert title here</title>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <style type=\"text/tailwindcss\">\r\n");
      out.write("        @theme {\r\n");
      out.write("        --color-clifford: #da373d;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .line {\r\n");
      out.write("            background: #ededed;\r\n");
      out.write("            height: 1px;\r\n");
      out.write("            flex: 1 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider2 {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider2 span {\r\n");
      out.write("            margin-right: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider span {\r\n");
      out.write("            flex: .2 0 auto;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: inherit;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #eye {\r\n");
      out.write("            width: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        #eye #eye-close {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #eye.open #eye-close {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        #eye.open #eye-open {\r\n");
      out.write("           display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #eye{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            right: 10px;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"bg-white w-[400px] shadow-lg mx-auto px-[40px] pb-5\">\r\n");
      out.write("        <h1 class=\"text-center !text-[22px] py-2 font-semibold\">Tạo tài khoản</h1>\r\n");
      out.write("        <a href=\"#\" class=\"flex items-center border-gray-500 border-1 rounded-[8px] mb-[12px] py-[12px] px-[20px]\">\r\n");
      out.write("            <svg fill=\"currentColor\" stroke=\"\" viewBox=\"0 0 16 17\" width=\"20\" height=\"20\"\r\n");
      out.write("                xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                <g clip-path=\"url(#clip0_2635_44439)\">\r\n");
      out.write("                    <path\r\n");
      out.write("                        d=\"M6.02293 16.5L6 9.5H3V6.5H6V4.5C6 1.8008 7.67151 0.5 10.0794 0.5C11.2328 0.5 12.2241 0.58587 12.5129 0.62425V3.44507L10.843 3.44583C9.53343 3.44583 9.27987 4.0681 9.27987 4.98124V6.5H13L12 9.5H9.27986V16.5H6.02293Z\">\r\n");
      out.write("                    </path>\r\n");
      out.write("                </g>\r\n");
      out.write("                <defs>\r\n");
      out.write("                    <clipPath id=\"clip0_2635_44439\">\r\n");
      out.write("                        <rect width=\"16\" height=\"16\" fill=\"white\" transform=\"translate(0 0.5)\"></rect>\r\n");
      out.write("                    </clipPath>\r\n");
      out.write("                </defs>\r\n");
      out.write("            </svg>\r\n");
      out.write("            <span class=\"text-[18px] ml-3\">Đăng nhập với Google</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"flex items-center border-gray-500 border-1 rounded-[8px] mb-[12px] py-[12px] px-[20px]\">\r\n");
      out.write("            <svg fill=\"currentColor\" stroke=\"\" viewBox=\"0 0 16 17\" width=\"20\" height=\"20\"\r\n");
      out.write("                xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                <path\r\n");
      out.write("                    d=\"M7.99991 4.16655C9.01809 4.16592 10.0036 4.52573 10.7819 5.18221L12.9619 3.10621C12.1251 2.33457 11.1199 1.76861 10.0261 1.45323C8.9324 1.13785 7.7802 1.08175 6.66099 1.28936C5.54178 1.49697 4.48636 1.96259 3.5785 2.64927C2.67064 3.33594 1.93532 4.22477 1.43091 5.24521L3.88858 7.13955C4.1752 6.27524 4.72649 5.52302 5.46438 4.98944C6.20226 4.45586 7.08932 4.16797 7.99991 4.16655Z\"\r\n");
      out.write("                    fill=\"#D94F3D\"></path>\r\n");
      out.write("                <path\r\n");
      out.write("                    d=\"M3.66662 8.49978C3.66724 8.03737 3.74219 7.57807 3.88862 7.13945L1.43096 5.24512C0.928241 6.25642 0.666626 7.37042 0.666626 8.49978C0.666626 9.62914 0.928241 10.7431 1.43096 11.7545L3.88862 9.86012C3.74219 9.4215 3.66724 8.9622 3.66662 8.49978Z\"\r\n");
      out.write("                    fill=\"#F2C042\"></path>\r\n");
      out.write("                <path\r\n");
      out.write("                    d=\"M15.0333 7.1665H8.03333V10.1665H12C11.764 11.0148 11.2234 11.7461 10.4817 12.2205L12.9203 14.1005C14.4787 12.7018 15.3943 10.4275 15.0333 7.1665Z\"\r\n");
      out.write("                    fill=\"#5085ED\"></path>\r\n");
      out.write("                <path\r\n");
      out.write("                    d=\"M10.4806 12.2204C9.72692 12.6518 8.86773 12.864 7.99991 12.8331C7.08932 12.8317 6.20226 12.5438 5.46438 12.0102C4.72649 11.4766 4.1752 10.7244 3.88858 9.86011L1.43091 11.7544C2.03796 12.9781 2.97439 14.0082 4.13489 14.7287C5.29539 15.4493 6.63391 15.8318 7.99991 15.8331C9.79736 15.8819 11.5494 15.2646 12.9192 14.0998L10.4806 12.2204Z\">\r\n");
      out.write("                </path>\r\n");
      out.write("            </svg>\r\n");
      out.write("            <span class=\"text-[18px] ml-3\">Đăng nhập với Facebook</span>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"divider\">\r\n");
      out.write("            <div class=\"line\"></div>\r\n");
      out.write("\r\n");
      out.write("            <span>OR</span>\r\n");
      out.write("            <div class=\"line\"></div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"\" class=\"mt-2\">\r\n");
      out.write("            <div class=\"mb-2\">\r\n");
      out.write("                <input type=\"text\" required class=\"form-control\" id=\"\" placeholder=\"Họ và tên*\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-2\">\r\n");
      out.write("                <input type=\"text\" required class=\"form-control\" id=\"\" placeholder=\"Tài khoản*\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-2\">\r\n");
      out.write("                <input type=\"email\" required class=\"form-control\" id=\"\" placeholder=\"Email*\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-2 relative\">\r\n");
      out.write("                <input type=\"password\" required class=\"form-control\" id=\"passwordInput\" placeholder=\"Mật khẩu*\">\r\n");
      out.write("                <div id=\"eye\" onclick=\"togglePassword(this, 'passwordInput')\">\r\n");
      out.write("                    <div id=\"eye-open\">\r\n");
      out.write("                    <svg viewBox=\"0 0 488.85 488.85\" className=\"w-18\">\r\n");
      out.write("                        <g>\r\n");
      out.write("                            <path\r\n");
      out.write("                                d=\"M244.425 98.725c-93.4 0-178.1 51.1-240.6 134.1-5.1 6.8-5.1 16.3 0 23.1 62.5 83.1 147.2 134.2 240.6 134.2s178.1-51.1 240.6-134.1c5.1-6.8 5.1-16.3 0-23.1-62.5-83.1-147.2-134.2-240.6-134.2zm6.7 248.3c-62 3.9-113.2-47.2-109.3-109.3 3.2-51.2 44.7-92.7 95.9-95.9 62-3.9 113.2 47.2 109.3 109.3-3.3 51.1-44.8 92.6-95.9 95.9zm-3.1-47.4c-33.4 2.1-61-25.4-58.8-58.8 1.7-27.6 24.1-49.9 51.7-51.7 33.4-2.1 61 25.4 58.8 58.8-1.8 27.7-24.2 50-51.7 51.7z\"\r\n");
      out.write("                                fill=\"#000000\" opacity=\"1\" data-original=\"#000000\" class=\"\">\r\n");
      out.write("                            </path>\r\n");
      out.write("                        </g>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"eye-close\">\r\n");
      out.write("                    <svg viewBox=\"0 0 512 512\" className=\"w-18\">\r\n");
      out.write("                        <g>\r\n");
      out.write("                            <g data-name=\"Layer 16\">\r\n");
      out.write("                                <path\r\n");
      out.write("                                    d=\"M419.72 419.72 92.26 92.27l-.07-.08a19 19 0 0 0-26.78 27l28.67 28.67a332.64 332.64 0 0 0-88.19 89 34.22 34.22 0 0 0 0 38.38C65.86 364 160.93 416 256 415.35a271.6 271.6 0 0 0 90.46-15.16l46.41 46.41a19 19 0 0 0 26.94-26.79zM256 363.74a107.78 107.78 0 0 1-98.17-152.18l29.95 29.95a69.75 69.75 0 0 0 82.71 82.71l29.95 29.95a107.23 107.23 0 0 1-44.44 9.57zM506.11 236.81C446.14 148 351.07 96 256 96.65a271.6 271.6 0 0 0-90.46 15.16l46 46a107.78 107.78 0 0 1 142.63 142.63l63.74 63.74a332.49 332.49 0 0 0 88.2-89 34.22 34.22 0 0 0 0-38.37z\"\r\n");
      out.write("                                    fill=\"#000000\" opacity=\"1\" data-original=\"#000000\" class=\"\"></path>\r\n");
      out.write("                                <path\r\n");
      out.write("                                    d=\"M256 186.26a69.91 69.91 0 0 0-14.49 1.52l82.71 82.7A69.74 69.74 0 0 0 256 186.26z\"\r\n");
      out.write("                                    fill=\"#000000\" opacity=\"1\" data-original=\"#000000\" class=\"\">\r\n");
      out.write("                                </path>\r\n");
      out.write("                            </g>\r\n");
      out.write("                        </g>\r\n");
      out.write("                    </svg>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"btn w-full mt-4 py-3 !font-bold text-white !bg-[#098642]\">Tiếp tục</button>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mt-3\">\r\n");
      out.write("                <a href=\"tailieu_dangnhap.jsp\">\r\n");
      out.write("                    <span class=\"text-gray-500\">Bạn đã có tài khoản?</span> <span href=\"#\"\r\n");
      out.write("                        class=\"font-normal text-[#b6020f]\">Đăng nhập ngay</span>\r\n");
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("    const togglePassword = (eyeIcon, idInput) => {\r\n");
      out.write("        const passwordInput = document.getElementById(idInput)\r\n");
      out.write("        console.log(passwordInput.type);\r\n");
      out.write("        eyeIcon.classList.toggle(\"open\")\r\n");
      out.write("        passwordInput.type = passwordInput.type === \"text\" ? \"password\" : \"text\";\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
